### ISSUE TITLE
 1

### ISSUE THREAD

**Issue by Sven-Moennich** [mmitch/fritz#11]

**Comment by mmitch** [comment]
Soll ich die Issue wieder herstellen oder ganz löschen?

Meine Vermutung: Zu 2-Factor fällt mir nur ein, dass bestimmte Funktionen (z.B. das Anmelden eines neuen Mobilteils) das Drücken einer Taste an der FritzBox erfordern. Da müsstest Du mal in Deine FritzBox-Konfiguration, insbesondere Sicherheit und Rechtemanagement gucken.

Welche Einstellung hast Du denn auslesen wollen, dass Du das Problem bekommen hast?

**Comment by Sven-Moennich** [comment]
Moin.
Lösch das bitte wieder.
Du hast ganz Recht. Es ist das drücken einer Taste oder wählen einer Nummer.
Das ist nicht deine Schuld.
Ich wollte den Link zu der export Datei.
Da muss ich mir was einfallen lassen.
Darum hab ich das versucht zu löschen. Aber hat's nur verschlimmert.

Danke fürs löschen
Sven

Christian Garbs <notifications@github.com> schrieb am Mo., 7. Mai 2018,
23:27:

**Comment by Sven-Moennich** [comment]
Oh. Sorry. Ich hab dich voll übersehen.
Mir würde Variante 1 Zusagen.
Mach was für dich das beste ist.
Vllt ist es ja ne Hilfe für andere.

Wenn man in der Weboberfläche das knopfdrücken deaktiviert funktioniert es
trotzdem nicht ohne. Hast du dir mal das PDF von AVM zu der zwei Faktor
auth Geschichte angesehen? Das bekomm ich irgendwie mit deinem Modul nicht
hin.
Ich hatte aber auch noch nicht soviel Zeit das energischer zu analysieren.

Sorry das ich dich wirklich so lange übersehen habe.
Du bist da ganz doof durch die Mail Filter durch und Grade nur durch Zufall
aufgefallen.

Christian Garbs <notifications@github.com> schrieb am Do., 17. Mai 2018,
21:03:
