### ISSUE TITLE
Error on installing on Raspberry Pi

### ISSUE THREAD

**Issue by helmar74** [mmitch/fritz#12]
Hi,

I want to reinstall my Raspberry Pi. By installing the cpan module i get this error:
`t/00.load.t ............... 1/1 # Testing Net::Fritz v0.0.9
t/00.load.t ............... ok
t/01.fritz-isnoerror.t .... ok
t/02.fritz-error.t ........ ok
t/03.fritz-box.t .......... ok
t/04.fritz-data.t ......... ok
t/05.fritz-action.t ....... ok
t/06.fritz-service.t ...... ok
t/07.fritz-device.t ....... ok
t/08.fritz-device-call.t .. ok
t/09.fritz-box-call.t ..... ok
t/10.fritz-configfile.t ... Can't locate Test/TempDir/Tiny.pm in @INC (you may need to install the Test::TempDir::Tiny module) (@INC contains: /root/.cpan/build/Net-Fritz-v0.0.9-1/blib/lib /root/.cpan/build/Net-Fritz-v0.0.9-1/blib/arch /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/arm-linux-gnueabihf/perl5/5.24 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base .) at t/10.fritz-configfile.t line 6.
BEGIN failed--compilation aborted at t/10.fritz-configfile.t line 6.
# Looks like your test exited with 2 before it could output anything.
t/10.fritz-configfile.t ... Dubious, test returned 2 (wstat 512, 0x200)
Failed 18/18 subtests
t/60.connect-http.t ....... skipped: Not running author tests
t/61.connect-https.t ...... skipped: Not running author tests
t/80.pod-link-check.t ..... skipped: Not running author tests
t/author-critic.t ......... skipped: these tests are for testing by the author
t/author-pod-coverage.t ... skipped: these tests are for testing by the author
t/author-pod-linkcheck.t .. skipped: these tests are for testing by the author
t/author-pod-syntax.t ..... skipped: these tests are for testing by the author

Test Summary Report
-------------------
t/10.fritz-configfile.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 18 tests but ran 0.
Files=18, Tests=97, 10 wallclock secs ( 0.41 usr  0.11 sys +  8.69 cusr  0.58 csys =  9.79 CPU)
Result: FAIL
Failed 1/18 test programs. 0/97 subtests failed.
Makefile:913: die Regel für Ziel „test_dynamic“ scheiterte
make: *** [test_dynamic] Fehler 255
  CGARBS/Net-Fritz-v0.0.9.tar.gz
one dependency not OK (Test::TempDir::Tiny); additionally test harness failed
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports CGARBS/Net-Fritz-v0.0.9.tar.gz`

Any idea, what i can try to install the module?

**Comment by mmitch** [comment]
From the log it indeed looks like _Test::TempDir::Tiny_ was not found.

You could either try to install only _Test::TempDir::Tiny_ and look at the installation logs to see what goes wrong (via `cpanm Test::TempDir::Tiny` or `cpan -i Test::TempDir::Tiny`)  
or you could install _Net::Fritz_ without running the tests as everything apart from _Test::TempDir::Tiny_ looked fine so far (`cpanm --notest Net::Fritz` or `cpan -Ti Net::Fritz `) – apart from running the tests the module is not needed.

**Comment by mmitch** [comment]
Did you find anything in the build logs or did the workaround work for you?

**Comment by helmar74** [comment]
> Did you find anything in the build logs or did the workaround work for you?

No, I copied the module from my old server, after that it worked. It's only a workaround but it's ok for me.
Maybe you can try to install from scratch on a raspberry pi. A few mor prerequisites must be fullfilled, as currently documentend.
