### ISSUE TITLE
$XDG_CONFIG_HOME/fritzrc as default config file location?

### ISSUE THREAD

**Issue by marschap** [mmitch/fritz#8]
Hi,

please consider using the config file from the default location according to the XDG Base Directory specification https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html .

What about e.g. the following logic  ;-)
1) try $XDG_CONFIG_HOME/fritzrc
2)  if $XDG_CONFIG_HOME is not set, try  $HOME/.config/firtzrc
3) only if .config/ does not exist, use ~/.fritzrc

Best
Peter

**Comment by mmitch** [comment]
good idea, I'll look into it

**Comment by mmitch** [comment]
Could you please have a look if the current HEAD version fixes the problem as intended?
