### ISSUE TITLE
Can't get WANIPConnection:1 to work (7490)

### ISSUE THREAD

**Issue by Skeeve** [mmitch/fritz#9]
Here is my code:

    use Net::Fritz::Box;

    my $fritz    = Net::Fritz::Box->new(username=>'none', password=>'SECRET');
    if ($fritz->error) {
        die $fritz->error;
    }
    # '/upnp/control/wanipconnection1';
    my $device = $fritz->discover();
    $device->errorcheck;

    my $service = $device->find_service('DeviceInfo:1');
    $service->errorcheck;

    my $response = $service->call('GetSecurityPort');
    $response->errorcheck;

    printf "SSL communication port is %d\n",
    $response->data->{NewSecurityPort};

    $service = $device->find_service('WANIPConnection:1');
    $service->errorcheck;

    $response = $service->call('GetInfo');
    $response->errorcheck;

    use Data::Dumper;
    $Data::Dumper::Indent=1;
    print Dumper $response
    
The output is:

    SSL communication port is 49443
    Net::Fritz::Error: s:Client UPnPError 401 Invalid Action

So the first part works, the second failed.

Trying to attach a dump of $device, but github won't let me.

**Comment by Skeeve** [comment]
I think I found the reason: Using the wrong service!

Found it here: https://github.com/openhab/openhab1-addons/issues/5283 Post by @tensberg

**Comment by mmitch** [comment]
Sorry, I was not fast enough to get back to you in time…

I ran into the same problem some time ago when I upgraded from the old German Telekom DSL to their new IP-only DSL.
I found out that you can call `GetDSLLinkInfo` on the `WANDSLLinkConfig` device. The resulting data has a `NewLinkType` attribute that is either `PPPoE` or `IP` which tells you if you have to use `WANPPPConnection` or `WANIPConnection`, see https://github.com/mmitch/rrd/blob/master/fritz.pl#L82-L103

I'll add that to the examples when I can find some time for it (added issue #10 so it does not get lost).
